name: AISA Monitor

on:
  schedule:
    - cron: "*/3 * * * *"

  workflow_dispatch:

jobs:
  monitor:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python check_aisa.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Save state
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add state.json

          git diff --cached --quiet || git commit -m "Update state"
          git push
